### ISSUE TITLE
Deepak GitHub Integration & Branch updates

### ISSUE THREAD

**Issue by vivek0908** [vivek0908/Bucket#5]
@deepak24ti  please integrate GITHub to your visual studio at home and map to branch DevDeepak.
@animeshmandal I have pushed the lates data and did FI to DevAnimesh.

I created Main branch and that has policy requirements to be pushed from Master. 
We will work on our individual branches and push the code to master, and then to Main(which will be not so frquent)

.In case master is screwed , we still have workng latest in Main. 

Open for suggestion and changes.

**Comment by deepak24ti** [comment]
mapping done
